stages:
  - test
  - report
  - pages

image: python:3.10-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
  policy: pull-push

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

# This job runs the tests
test_job:
  stage: test
  script:
    - pytest --alluredir=allure-results
  artifacts:
    when: always
    paths:
      - allure-results/
    expire_in: 1 day

# This job generates the Allure report from the test results
generate_allure_report:
  stage: report
  image: openjdk:11-jre-slim
  script:
    - apt-get update -y
    - apt-get install -y wget unzip
    - wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.zip
    - unzip allure-commandline-2.27.0.zip
    - chmod +x allure-2.27.0/bin/allure
    - ./allure-2.27.0/bin/allure generate allure-results -o public --clean
  artifacts:
    paths:
      - public
    expire_in: 1 day
  dependencies:
    - test_job

# This job publishes the report to GitLab Pages
pages:
  stage: pages
  script:
    - echo "Publishing Allure report to GitLab Pages"
  artifacts:
    paths:
      - public
    expire_in: 30 days
  needs:
    - generate_allure_report
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH