name: Python E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Add this step to install the Chrome browser and driver
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest tests
      run: pytest --alluredir=allure-results

    - name: Generate Allure report
      if: always()
      uses: simple-elf/allure-report-action@v1.7
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_history: allure-history

    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report